---
title: "Code Appendix"
author: "Isabel Arvelo"
date: '2022-04-04'
output:
  pdf_document: default
  html_document: default
---

```{r, include = FALSE}
library(BatchGetSymbols)
library(dplyr)
```

```{r}
downloadPriceDF <- function(stock, start = 2010, nyears = 10) {
  
  #String manipulation to find dates 
  fd_string <- paste(as.character(start), "01", "01", sep = "-")
  ld_year <- start + nyears
  ld_string <- paste(as.character(ld_year), "01", "01", sep = "-")
  
  #Convert dates to date type to match it in dataset 
  first_date <-as.Date(fd_string)
  last_date <- as.Date(ld_string)
  
  #download stock data for given ticker and date range
  stockData <- BatchGetSymbols(tickers = stock, 
                             first.date = first_date, 
                             last.date = last_date, 
                             be.quiet = TRUE)
  
  #extract ticker data
  stockPrices <- stockData$df.tickers
  
  #cast dates as characters 
  stockPrices$date <- as.character(stockPrices$ref.date)
  stockPrices$price <- stockPrices$price.adjusted
  stockDF <- stockPrices[  ,c("date", "price")]
  
  return(stockDF)
}
```


```{r}
downloadStockPairDF <- function(stock1, stock2, start = 2010, nyears = 1) {
  
  stock1_df <- downloadPriceDF(stock1, start = start, nyears = nyears)
  stock2_df <-downloadPriceDF(stock2, start = start, nyears = nyears)
  
  not_aligned = 0 
  n = length(stock1_df)
  
  if ( (length(stock1_df) > length(stock2_df)) | (length(stock1_df) < length(stock2_df)) |
       (nrow(stock1_df) != nrow(stock1_df)) ) {
    not_aligned = 1
  } 

  if (nrow(stock1_df) == 0 ) {
    stop("No Data Available for Stock 1")
  }
  if (nrow(stock2_df) == 0 ) {
    stop("No Data Available for Stock 2")
  }
  
  for (i in 1:n) {
    if ( !identical(stock1_df$date[i], stock2_df$date[i]) ) {
      not_aligned = 1
    }
  }
  
  if (not_aligned) {
    print("Original date ranges are different. May be excluding available data")
    aligned_dates <- merge(stock1_df, stock2_df, by="date", all = T)
    stockPairDF <- aligned_dates[complete.cases(aligned_dates), ]
    colnames(stockPairDF) <- c("date", "stock1" , "stock2")
  } else {
    stockPairDF <- data.frame(stock1 = stock1_df$price, stock2 = stock2_df$price)
  }
  
  stockPairDF$ratio <- stockPairDF$stock1/stockPairDF$stock2
  
  return(stockPairDF)
}
```



```{r}
plotStocks <- function(stocksDF) {
  #create time series 
  stock1_ts <- ts(stocksDF$stock1, start = 1, end = nrow(stocksDF), frequency = 1)
  stock2_ts <- ts(stocksDF$stock2, start = 1, end = nrow(stocksDF), frequency = 1)
  ts.plot(stock1_ts, stock2_ts, main = "Stock Prices Over Time",gpars= list(col=rainbow(2)))
}
```


```{r}
plotRatio <- function(stocksDF, k = 1) {
    ratio_ts <- ts(stocksDF$ratio, start = 1, end = nrow(stocksDF), frequency = 1)
    ts.plot(ratio_ts, main = "Ratio of Prices Over Time", ylab = "Ratio")
    
    sd = sd(stocksDF$ratio)
    mean = mean(stocksDF$ratio)
    
    upper_lim = mean + (k * sd)
    lower_lim = mean - (k * sd)
    
    abline(h = mean, col = "blue")
    abline(h = upper_lim, col="darkgreen", lwd=3, lty=3)
    abline(h = lower_lim, col="darkgreen", lwd=3, lty=3)
    
    legend("topright", legend=c("mean", paste("mean +/-", floor(k * 100) / 100, "sd", sep = " ")),
       col=c("blue", "darkgreen"), lty=c(1,3), cex=0.8)

}
```

```{r}
findPositions <- function(ratio, m, s, k = 1) {
  
    positions <- list()
    
    n <- length(ratio) #max time horizon 
    uBound <-  m + (s*k)
    lBound <-  m - (s*k)
    
    currDay <- 1
    
    while ( currDay < n ) {
      
      possibleOpenDays <- ( (ratio > uBound) | (ratio < lBound) ) & (1:n > currDay)
      
      if (any(possibleOpenDays)) {
        openDay <- which(possibleOpenDays)[1]
      
      if (ratio[openDay] > uBound) { 
        highLow <- 1
        currDay <- openDay + 1
        while (ratio[currDay] > m & currDay < n){
          currDay <- currDay +1
        }
          }
      if (ratio[openDay] < lBound) {
        highLow <- -1
        currDay <- openDay + 1
        while (ratio[currDay] < m & currDay < n) {
          currDay <- currDay + 1
        }
      }
      if (currDay > n ) {
        currDay <- n
      }
      closeDay <- currDay
      positions[[length(positions)+1]] <- c(openDay, closeDay, highLow)
      } 
      else {break}
    }
    
    return(positions)
    
}
```

```{r}
addPositions <- function(ratio, positions, k) {
  
  for (i in 1:length(positions)) {
    x_start= as.integer(positions[[i]][[1]]) 
    x_end = as.integer(positions[[i]][[2]]) 
    points(x_start, ratio[x_start], col = "green", pch = 1)
    points(x_end, ratio[x_end], col = "red", pch = 1)
  }
  
}
```



```{r}
positionProfit <- function(stocksDF, positions, net = TRUE) {
  if (length(positions) == 0) {
    profits <- 0
    return(profits)
  }
  
  nPositions <- length(positions)
  profits <- numeric(nPositions)
  fixedFee <-0.003 
  
  for (i in 1:nPositions) {
    openPosition <- positions[[i]][[1]]
    closePosition <- positions[[i]][[2]]
    
    # number of shares using prices when we open the positions
    shares1 <- 1 / stocksDF$stock1[openPosition]
    shares2 <- 1 / stocksDF$stock2[openPosition]
    
    highLow <- positions[[i]][[3]]
    
    profit1 <- -1 * highLow * shares1 * stocksDF$stock1[closePosition]
    profit2 <-  highLow * shares2 * stocksDF$stock2[closePosition]

    
    fees <- fixedFee * (1 + 1 + abs(profit1) + abs(profit2))
    
    netprofit <- profit1 + profit2 - fees
    
    profits[i] <- netprofit
     }
  
  if (!net) {return(profits) }
  
  else {return(sum(profits)) }
}

```

```{r}
findOptimalK <- function(stocksDF, plot = FALSE) {
  ratio <- stocksDF$ratio
  m <- mean(ratio)
  s <- sd(ratio)
  
  kmax <- max(sapply(ratio-m, abs)) / s
  kvalues <- seq(0, kmax, length = 100)
  
  positionvecs <- sapply(kvalues, function(x) findPositions(ratio = ratio, m = m, s = s, k = x))
  profits <- sapply(positionvecs, function(x) positionProfit(stocksDF = stocksDF, positions = x, net = TRUE))
                  
  optimalK <- kvalues[which.max(profits)]
  
  if (plot) {
    plot(profits~kvalues, col=ifelse(kvalues==optimalK, "red", "black"),
    pch=ifelse(kvalues==optimalK, 20, 1), cex=ifelse(kvalues==optimalK, 2, 1), main =
      "Optimal k value")
    lines(kvalues, profits)
  }

  return(optimalK) 
         
}

```

```{r}
evalPlot <- function(stocksDF, k = 1, sd = 1, mean = 1) {
    ratio_ts <- ts(stocksDF$ratio, start = 1, end = nrow(stocksDF), frequency = 1)
    ts.plot(ratio_ts, main = "Ratio of Prices Over Time (Test Data)", ylab = "Ratio")
    
    
    upper_lim = mean + (k * sd)
    lower_lim = mean - (k * sd)
    
    abline(h = mean, col = "blue")
    abline(h = upper_lim, col="darkgreen", lwd=3, lty=3)
    abline(h = lower_lim, col="darkgreen", lwd=3, lty=3)
    
    legend("topright", legend=c("mean (training data)", paste("mean +/-", floor(k * 100)
                                                              / 100, "sd", sep = " ")),
    col=c("blue", "darkgreen"), lty=c(1,3), cex=0.8)

}
```

```{r}
evaluatePairsTrading <- function(stocksDF, trainingFrac = 0.5, plot = FALSE) {
    n= nrow(stocksDF)
    train_cutoff = floor(trainingFrac*n)
    
    training =  stocksDF[1:train_cutoff, ]
    test = stocksDF[(train_cutoff+1):n, ]
    
    train_ratio <- training$ratio
    train_m <- mean(train_ratio)
    train_s <- sd(train_ratio)
    
    train_k <- findOptimalK(training, plot = FALSE)
    test_positions <- findPositions(test$ratio, m = train_m, s = train_s, k = train_k)
    profit <- positionProfit(test, test_positions) 
    
    if (plot) {
      if (length(test_positions) > 0 ) {
        profit_vec <-positionProfit(test, test_positions, net = FALSE) 
        evalPlot(test, k = train_k, sd = train_s, mean = train_m)
        addPositions(test$ratio, test_positions)
        for (i in 1:length(test_positions)) {
          text(test_positions[[i]][[2]], test$ratio[test_positions[[i]][[2]]],
               as.character(floor(profit_vec[i] * 100) / 100), cex = .5 , pos = 1)
        }
      } else {
        evalPlot(test, k = train_k, sd = train_s, mean = train_m)
      }
      
    }
    
    return(profit)
}
```


```{r}
simulateStockPair <- function (n=1000, sigma1=1, sigma2=1, rho=1, psi=0, b1=0, b2=0, plot=FALSE) {
  
  x1 = 10
  x2 = 20
  
  x_1i <- list(x1)
  x_2i <- list(x2)
  
  e_1 <- rnorm(n, 0, sigma1 ^ 2)
  e_2 <- rnorm(n, 0, sigma2 ^ 2)
  
  a1 <- 20
  a2 <- 30
  
  y_1i <- list()
  y_2i <- list()
  
 
  for (i in 2:n) {
    x_1i[i] <-
      rho * x_1i[[i - 1]] + (1 - rho) * psi * x_2i[[i - 1]] + e_1[[i]]
    x_2i[i] <-
      rho * x_2i[[i - 1]] + (1 - rho) * psi * x_1i[[i - 1]] + e_2[[i]]
  }
  
  x_1i <- unlist(x_1i)
  x_2i <- unlist(x_2i)
  
  y_1i <- a1 + b1 * 1:length(x_1i) + x_1i
  y_2i <- a2 + b2 * 1:length(x_2i) + x_2i
  
  stocksdf <- data.frame(stock1 = y_1i, stock2 = y_2i)
  
  stocksdf$ratio <- (stocksdf$stock1) / (stocksdf$stock2)
  
  if (plot) {
    plotStocks(stocksdf)
  }
  
  return(stocksdf)
  }
```

```{r}
simulateDistribution <-function(nreps = 100, returnCorrelation = FALSE, ...) {
    trials <- list()
    cor <- list()
    
    if (returnCorrelation) {
      for (i in 1:nreps) {
        sim <- simulateStockPair(...)
        cor[[i]] <-cor(sim$stock1, sim$stock2)
      }
      return (unlist(cor))
    }
    
    else {
      for (i in 1:nreps) {
        trials[[i]] <- simulateStockPair(...)
      }
      dist <- lapply(trials, evaluatePairsTrading)
    }
    
    return(unlist(dist))
  }
```


## Extension 2 

```{r}
positions <- function(stocksDF, trainingFrac = 0.5, plot = FALSE) {
    n= nrow(stocksDF)
    train_cutoff = floor(trainingFrac*n)
    
    training =  stocksDF[1:train_cutoff, ]
    test = stocksDF[(train_cutoff+1):n, ]
    
    train_ratio <- training$ratio
    train_m <- mean(train_ratio)
    train_s <- sd(train_ratio)
    
    train_k <- findOptimalK(training, plot = FALSE)
    test_positions <- findPositions(test$ratio, m = train_m, s = train_s, k = train_k)
    
    
    return(test_positions)
}

listToDf <- function(nestedlist) {
  if (length(nestedlist) >  0 ) {
      df= as.data.frame(t(as.data.frame(nestedlist)))
  rownames(df)<-NULL
  df %>% 
  rename(
    Open = V1 ,
    Close = V2
    )
  }
}


dfToDays <- function(df, openDays, closeDays) {
  df_pos <- positions(df)
  df_df <- listToDf(df_pos)
  return(df_df)
}

```


```{r}
openDays <- c()
closeDays <- c()

#all stocks downloaded have same date range - ensured by not receiving any of the warning messages implemented with extension 1 

#healthcare
healthcare_1 <- downloadStockPairDF("PFE", "JNJ", start = 2010, nyears = 10)
healthcare_2 <- downloadStockPairDF("UNH", "HUM", start = 2010, nyears = 10)
healthcare_3 <- downloadStockPairDF("AFL", "CI", start = 2010, nyears = 10)

healthcare_1_df <- dfToDays(healthcare_1)
healthcare_2_df <- dfToDays(healthcare_2)
healthcare_3_df <- dfToDays(healthcare_3)

#materials
materials_1 <- downloadStockPairDF("ECL", "APD", start = 2010, nyears = 10)
materials_2 <- downloadStockPairDF("APD", "DD", start = 2010, nyears = 10)

materials_1_df <- dfToDays(materials_1)
materials_2_df <- dfToDays(materials_2)

#real estate
re_1 <- downloadStockPairDF("O", "ARE", start = 2010, nyears = 10)
re_2 <- downloadStockPairDF("SPG", "DRE", start = 2010, nyears = 10)
re_3 <- downloadStockPairDF("ARE", "SUI", start = 2010, nyears = 10)

re_1_df <- dfToDays(re_1)
re_2_df <- dfToDays(re_2)
re_3_df <- dfToDays(re_3)


#consumer staples 
cs_1 <- downloadStockPairDF("PEP", "COKE", start = 2010, nyears = 10)
cs_2 <- downloadStockPairDF("PG", "UL", start = 2010, nyears = 10)
cs_3 <- downloadStockPairDF("COST", "WMT", start = 2010, nyears = 10)

cs_1_df <- dfToDays(cs_1)
cs_2_df <- dfToDays(cs_2)
cs_3_df <- dfToDays(cs_3)

#consumer discretionary
cd_1 <- downloadStockPairDF("MCD", "SBUX", start = 2010, nyears = 10)
cd_2 <- downloadStockPairDF("M", "JWN", start = 2010, nyears = 10)
cd_3 <- downloadStockPairDF("H", "MAR", start = 2010, nyears = 10)
cd_4 <- downloadStockPairDF("NKE", "ADDYY", start = 2010, nyears = 10)

cd_1_df <- dfToDays(cd_1)
cd_2_df <- dfToDays(cd_2)
cd_3_df <- dfToDays(cd_3)
cd_4_df <- dfToDays(cd_4)


#utilities
util_1 <- downloadStockPairDF("ED", "DUK", start = 2010, nyears = 10)
util_2 <- downloadStockPairDF("NRG", "CNP", start = 2010, nyears = 10)

util_1_df <- dfToDays(util_1)
util_2_df <- dfToDays(util_2)

#energy
energy_1 <- downloadStockPairDF("RYDAF", "CVX", start = 2010, nyears = 10)
energy_2 <- downloadStockPairDF("PXD", "EOG", start = 2010, nyears = 10)
energy_3 <- downloadStockPairDF("XOM","CVX", start = 2010, nyears = 10)

energy_1_df <- dfToDays(energy_1)
energy_2_df <- dfToDays(energy_2)
energy_3_df <- dfToDays(energy_2)

#industrials
indus_1 <- downloadStockPairDF("RTX", "HON", start = 2010, nyears = 10)
indus_2 <- downloadStockPairDF("LMT", "GD", start = 2010, nyears = 10)

indus_1_df <- dfToDays(indus_1)
indus_2_df <- dfToDays(indus_2)

#communication services 
com_serv_1 <- downloadStockPairDF("VZ","T", start = 2010, nyears = 10)
com_serv_2 <- downloadStockPairDF("NFLX","DIS", start = 2010, nyears = 10)
com_serv_3 <- downloadStockPairDF("NXST","TGNA", start = 2010, nyears = 10)

com_serv_1_df <- dfToDays(com_serv_1)
com_serv_2_df<- dfToDays(com_serv_2)
com_serv_3_df <- dfToDays(com_serv_3)


#financials 
fin_1 <- downloadStockPairDF("MA", "V", start = 2010, nyears = 10)
fin_2 <- downloadStockPairDF("JPM", "MS", start = 2010, nyears = 10)
fin_3 <- downloadStockPairDF("BAC", "C", start = 2010, nyears = 10)

fin_1_df <- dfToDays(fin_1)
fin_2_df <- dfToDays(fin_2)
fin_3_df <- dfToDays(fin_3)


#information technology
tech_1 <- downloadStockPairDF("ACN", "ORCL", start = 2010, nyears = 10)
tech_2 <- downloadStockPairDF("AAPL", "MSFT", start = 2010, nyears = 10)

tech_1_df <- dfToDays(tech_1)
tech_2_df <- dfToDays(tech_2)

openDays <- append(openDays, c(healthcare_1_df$Open, healthcare_2_df$Open,
                               healthcare_3_df$Open, 
                               materials_1_df$Open, materials_2_df$Open,
                               re_1_df$Open, re_2_df$Open, re_3_df$Open,
                               indus_1_df$Open, indus_2_df$Open,
                               energy_1_df$Open, energy_2_df$Open, energy_3_df$Open, 
                               cs_1_df$Open, cs_2_df$Open, cs_3_df$Open, 
                               cd_1_df$Open, cd_2_df$Open,cd_3_df$Open, cd_4_df$Open,
                               util_1_df$Open,util_2_df$Open, com_serv_1_df$Open,
                               com_serv_2_df$Open, com_serv_3_df$Open, fin_1_df$Open,
                               fin_2_df$Open,  fin_3_df$Open, tech_1_df$Open,
                               tech_2_df$Open
                               ))

closeDays <- append(closeDays, c(healthcare_1_df$Close, healthcare_2_df$Close,
                                 healthcare_3_df$Close, materials_1_df$Close,
                                 materials_2_df$Close, re_1_df$Close, re_2_df$Close,
                                 re_3_df$Close, indus_1_df$Close, indus_2_df$Close,
                                 energy_1_df$Close,
                                 energy_2_df$Close, energy_3_df$Close, cs_1_df$Close,
                                 cs_2_df$Close,
                                 cs_3_df$Close,
                                 cd_1_df$Close, cd_2_df$Close, cd_3_df$Close,
                                 cd_4_df$Close, util_1_df$Close,
                                 util_2_df$Close, com_serv_1_df$Close,
                                 com_serv_2_df$Close, com_serv_3_df$Close,
                                 fin_1_df$Close,
                                 fin_2_df$Close,fin_3_df$Close, tech_1_df$Close,
                                 tech_2_df$Close ))


fulldates <- downloadPriceDF("AFL", 2010, 10)
decadedates <- fulldates $date

testLength = length(openDays)
OpenDates <- c()
for (i in 1:testLength) {
  OpenDates <- append(OpenDates, decadedates[openDays[i] + 1258])
}

CloseDates <- c()
for (i in 1:testLength) {
  CloseDates <- append(CloseDates, decadedates[closeDays[i] + 1258])
}
```







